### ISSUE TITLE
Nanites causing grid simulation to freeze

### ISSUE THREAD

**Issue by skyraze** [nukeguard/NaniteConstructionSystem#17]
I've been having this problem where my nanites would not work at all whether its mining or construction. it seems to be linked with the amount of nanites currently active, but i still have to pinpoint when the problems occur. however currently, if i run my nanite miner ship (carries 4 NCF each with 3 mining upgrades, rest speed) they show the usual "1000 possible targets" as well as shows "current mining streams" as 10, but then active nanites shows zero and it receives an error saying that the object is already targeted by another factory. once this happens, nothing else works. doors don't open, medical bays dont recharge or give oxygen/ hydrogen, air vents don't pressurize, refineries and assemblers stop working, thrusters show they are off.(the ship can move, but rubber bands back into place) I have more than enough power as i went as far as to go overkill on power in creative to see if that fixes it.

currently there is a total of 8 nanite factories in the world, 4 on the ship and 4 on a station. the station ones work fine until the ship factories activate.

What makes it even weirder is that all 8 factories were working all at once in the same area and never had a hiccup. it seemed until recently that they stopped working. I even went and updated the max streams for mining and construction in case they were hitting some sort of max.

**Comment by Fank** [comment]
1. Singleplayer or Multiplayer?
2. Can you upload the world?

Havn't tested nanite mining yet.
saw "object is already targeted by another factory" from other users too, looks like its related to mining.

**Comment by skyraze** [comment]
Here is the log for the nanites, i don't see anything immediate that pops up, however i saw this error, looks like its related to building a nanite beacon. i'm uploading a video rn showing the issue im getting and that i can cause it repetitively.



[17:43:52] ADDING Repair Beacon: 114723527446544959
[17:43:52] Update Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at NaniteConstructionSystem.Entities.Effects.NaniteBeaconEffect..ctor(MyCubeBlock owner, Vector3 localOffset, Vector4 color)
   at NaniteConstructionSystem.Entities.Beacons.NaniteBeaconConstruct.Update()
   at NaniteConstructionSystem.NaniteConstructionManager.ProcessBeaconBlocks()
   at NaniteConstructionSystem.NaniteConstructionManager.UpdateBeforeSimulation()
[17:43:52] ProcessTargetsParallel() Error 4: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NaniteConstructionSystem.Entities.Targets.NaniteConstructionTargets.CheckBeacons()
   at NaniteConstructionSystem.Entities.Targets.NaniteConstructionTargets.ParallelUpdate(List`1 gridList, List`1 blocks)
   at NaniteConstructionSystem.Entities.NaniteConstructionBlock.ProcessTargetsParallel()

[NaniteConstructionSystem.log](https://github.com/nukeguard/NaniteConstructionSystem/files/2238361/NaniteConstructionSystem.log)

**Comment by Fank** [comment]
Will be fixed with #27, nothing i can do now.
