### ISSUE TITLE
NullReferenceException in Beacons

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#22]
```
Update Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at NaniteConstructionSystem.Entities.Effects.NaniteBeaconEffect..ctor(MyCubeBlock owner, Vector3 localOffset, Vector4 color)
   at NaniteConstructionSystem.Entities.Beacons.NaniteBeaconConstruct.Update()
   at NaniteConstructionSystem.NaniteConstructionManager.ProcessBeaconBlocks()
   at NaniteConstructionSystem.NaniteConstructionManager.UpdateBeforeSimulation()
```

**Comment by nukeguard** [comment]
would this have to do with this null reference too from NUHOL?
[09:53:38] ADDING Mining Hammer: 101572799989574627
[09:53:38] Update Error: System.NullReferenceException: Object reference not set to an instance of an object.
at NaniteConstructionSystem.Entities.Effects.NaniteBeaconEffect..ctor(MyCubeBlock owner, Vector3 localOffset, Vector4 color)
at NaniteConstructionSystem.Entities.Beacons.NaniteMining.Initialize()
at NaniteConstructionSystem.Entities.Beacons.NaniteMining.Update()
at NaniteConstructionSystem.NaniteConstructionManager.ProcessMiningBlocks()
at NaniteConstructionSystem.NaniteConstructionManager.UpdateBeforeSimulation()

**Comment by nukeguard** [comment]
specific condition was placed on a large ship grid and not station

**Comment by Fank** [comment]
I know it happend to every block sometimes, but don't know why.
I'm unable to fix.

**Comment by nukeguard** [comment]
just saw this comment: do NOT use deconstruction beacon on small ships, tested multiple times on diffrent computers, made the graphic card crash every time.

Idk if it's an isolated issue, but will ask for crash log
