### ISSUE TITLE
Add ds plugin which provide metric information

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#50]
It should start a http server and provide a json api, with following information:
- About of each block which calculates stuff
- Information about runtime like durations (e.g. ore detector duration for scanning voxels)
- And so on

It should a read only api.
Information about plugins https://forum.keenswh.com/threads/1-187-dedicate-server-plugins.7401644/

**Comment by Fank** [comment]
Last changes pushed to branch fk_v2plugin issue stopped because of unfixable collission with cast a gamelogic with a other class of the nanite system.
Because `NaniteConstructionSystem.Entities.Detectors.BigNaniteOreDetectorLogic` which is compiled in se from the mod on startup does not match with `NaniteConstructionSystem.Entities.Detectors.BigNaniteOreDetectorLogic` from the plugin dll, and because of this the gamelogic could not be casted and always return `null`.

```
2018-08-16 22:21:21.161 - Thread:  44 ->  GameLogic: NaniteConstructionSystem.Entities.Detectors.BigNaniteOreDetectorLogic
2018-08-16 22:21:21.161 - Thread:  44 ->  False
2018-08-16 22:21:21.169 - Thread:  44 ->  System.NullReferenceException: Object reference not set to an instance of an object.
   at NanitePlugin.Plugin.<Listen>b__9_1(Object c)
2018-08-16 22:21:21.353 - Thread:  45 ->  GameLogic: NaniteConstructionSystem.Entities.Detectors.BigNaniteOreDetectorLogic
2018-08-16 22:21:21.353 - Thread:  45 ->  False
2018-08-16 22:21:21.359 - Thread:  45 ->  System.NullReferenceException: Object reference not set to an instance of an object.
   at NanitePlugin.Plugin.<Listen>b__9_1(Object c)
```
