### ISSUE TITLE
NullReferenceException: Object reference not set

### ISSUE THREAD

**Issue by VasVadum** [nukeguard/NaniteConstructionSystem#59]
I seem to get this error a lot lately, particularly in recent updates of the game.  In my case right now, my laptop ran out of RAM, the game was taking 25GB+ and hit the critical point and crashed, destroying my save file in the process.  When I loaded a backup save, this error starts happening.

```
Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at NaniteConstructionSystem.NaniteConstructionManager.Initialize()
   at NaniteConstructionSystem.NaniteConstructionManager.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```
Log File: 
[SpaceEngineers.log](https://github.com/nukeguard/NaniteConstructionSystem/files/2330804/SpaceEngineers.log)

Save File:
... Grr.. It suddenly started working again, why is this error so hard to replicate.

**Comment by skyraze** [comment]
Same here, can't even play anymore. Took up all 16 gb of RAM, plus 16 gb of
pagefile cache, then I got a blue screen

On Aug 29, 2018 12:23 AM, "VasVadum" <notifications@github.com> wrote:

I seem to get this error a lot lately, particularly in recent updates of
the game. In my case right now, my laptop ran out of RAM, the game was
taking 25GB+ and hit the critical point and crashed, destroying my save
file in the process. When I loaded a backup save, this error starts
happening.

Exception occured: System.NullReferenceException: Object reference not
set to an instance of an object.
   at NaniteConstructionSystem.NaniteConstructionManager.Initialize()
   at NaniteConstructionSystem.NaniteConstructionManager.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action
disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)

Log File:
SpaceEngineers.log
<https://github.com/nukeguard/NaniteConstructionSystem/files/2330804/SpaceEngineers.log>

Save File:
... Grr.. It suddenly started working again, why is this error so hard to
replicate.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nukeguard/NaniteConstructionSystem/issues/59>, or mute
the thread

**Comment by Fank** [comment]
Singleplayer?

**Comment by skyraze** [comment]
in general, it seems to have this issue in the main menu too.

**Comment by Fank** [comment]
Wat?

**Comment by VasVadum** [comment]
Fank, it happens to me during game loading, whether single player or private server or friends only server.

**Comment by VasVadum** [comment]
I'll upload a save when it happens again, I have around 80 mods.

**Comment by SplenectomY** [comment]
NaniteConstructionManager.Initialize() is replaced with NaniteConstructionManagerSync.Initialize() in V2 and this issue will likely be fixed.
