### ISSUE TITLE
Crash when accessing inventory directly from Old rusty factory

### ISSUE THREAD

**Issue by nukeguard** [nukeguard/NaniteConstructionSystem#60]
I can access inventory through another cargo/inventory point, but if I access inventory through block it crashes.

Exception occured: System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyCargoContainer' to type 'SpaceEngineers.Game.Entities.Blocks.MyShipWelder'.
   at Sandbox.Game.Gui.MyTerminalControl`1.Sandbox.Game.Gui.ITerminalControl.IsVisible(MyTerminalBlock block)
   at Sandbox.Graphics.GUI.MyGuiControlGenericFunctionalBlock.RecreateBlockControls()
   at Sandbox.Graphics.GUI.MyGuiControlGenericFunctionalBlock..ctor(MyTerminalBlock[] blocks)
   at Sandbox.Game.Gui.MyTerminalControlPanel.SelectBlocks()
   at Sandbox.Game.Gui.MyTerminalControlPanel.PopulateBlockList(MyTerminalBlock[] selectedBlocks)
   at Sandbox.Game.Gui.MyTerminalControlPanel.Init(IMyGuiControlsParent controlsParent, MyPlayer controller, MyCubeGrid grid, MyTerminalBlock currentBlock, MyGridColorHelper colorHelper)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.CreateTabs()
   at Sandbox.Game.Gui.MyGuiScreenTerminal.RecreateControls(Boolean constructor)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.Show(MyTerminalPageEnum page, MyCharacter user, MyEntity interactedEntity)
   at SpaceEngineers.Game.Entities.UseObjects.MyUseObjectInventory.Use(UseActionEnum actionEnum, IMyEntity entity)
   at Sandbox.Game.Entities.Character.MyCharacter.Use()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.HandleUnhandledInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)

**Comment by nukeguard** [comment]
though, now that I see that it says SpaceEngineers.Game.Entities.Blocks.MyShipWelder I may change block type to welder to see if this fixes that issue.

**Comment by nukeguard** [comment]
Switching old nanite factory MyObjectBuilder type to welder fixed this issue.
