### ISSUE TITLE
Crash when placing any block in mod

### ISSUE THREAD

**Issue by nukeguard** [nukeguard/NaniteConstructionSystem#63]
```
Exception occured: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NaniteConstructionSystem.Entities.NaniteConstructionBlock..ctor(IMyEntity entity)
   at NaniteConstructionSystem.Entities.NaniteConstructionLogic.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyCompositeGameLogicComponent.Init(MyObjectBuilder_EntityBase objectBuilder)
   at VRage.Game.Entity.MyEntity.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyCubeBlock.Init(MyObjectBuilder_CubeBlock builder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at SpaceEngineers.Game.Entities.Blocks.MyOxygenFarm.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MySlimBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid, MyCubeBlock fatBlock)
   at Sandbox.Game.Entities.MyCubeGrid.AddCubeBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge, MyCubeBlockDefinition blockDefinition)
   at Sandbox.Game.Entities.MyCubeGrid.AddBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge)
   at Sandbox.Game.Entities.MyCubeGrid.BuildBlock(MyCubeBlockDefinition blockDefinition, Vector3 colorMaskHsv, Vector3I min, Quaternion orientation, Int64 owner, Int64 entityId, MyEntity builderEntity, MyObjectBuilder_CubeBlock blockObjectBuilder, Boolean updateVolume, Boolean testMerge, Boolean buildAsAdmin)
   at Sandbox.Game.Entities.MyCubeGrid.BuildBlocksSuccess(Vector3 colorMaskHsv, HashSet`1 locations, HashSet`1 resultBlocks, MyEntity builder, Boolean instantBuilt, Int64 ownerId)
```

**Comment by Fank** [comment]
Thats a bug with `MyOxygenFarm` its fixed in v2
