### ISSUE TITLE
NaniteConstructionBlock.ScanForTargets exception: Destination array not long enough

### ISSUE THREAD

**Issue by SplenectomY** [nukeguard/NaniteConstructionSystem#73]
ScanForTargets Error: System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NaniteConstructionSystem.Entities.NaniteConstructionBlock.ProcessAssemblerQueue()
   at NaniteConstructionSystem.Entities.NaniteConstructionBlock.<ScanForTargets>b__58_0()

Leaving this here so I don't lose this. Will fix when I have time.

**Comment by SplenectomY** [comment]
Gonna fix this one too, so I'm just going to lump it into this issue: ProcessTargetsParallel() Error System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Sandbox.Game.MyInventory.GetObjectBuilder()
   at VRage.Game.Components.MyComponentContainer.Serialize(Boolean copy)
   at VRage.Game.Entity.MyEntity.GetObjectBuilder(Boolean copy)
   at Sandbox.Game.Entities.Character.MyCharacter.GetObjectBuilder(Boolean copy)
   at NaniteConstructionSystem.Entities.Targets.NaniteFloatingTargets.ParallelUpdate(List`1 gridList, List`1 blocks)
   at NaniteConstructionSystem.Entities.NaniteConstructionBlock.ProcessTargetsParallel()
