### ISSUE TITLE
Nanite Construction Factory 2.0 DEV: Exception at NaniteConstructionBlock.ProcessTargets

### ISSUE THREAD

**Issue by jusitnboggs** [nukeguard/NaniteConstructionSystem#81]
18:43:45.6532 [INFO]   Keen: Nanite Construction Factory: Exception at NaniteConstructionBlock.ProcessTargets:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NaniteConstructionSystem.Entities.Targets.NaniteMiningTargets.FindTargets(Dictionary`2& available, List`1 blockList)
   at NaniteConstructionSystem.Entities.NaniteConstructionBlock.ProcessTargets()

**Comment by SplenectomY** [comment]
@jusitnboggs This is a harmless thing that pops up every once in a while. I haven't decided whether its worth the performance hit to use some sort of concurrent collection to handle these iterations or whether i should just swallow the exceptions, as they don't corrupt in-game data. So, your mod is fine, it's working properly. Just still in development ;)
